/*
 * OpenDota API
 * # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  **Beginning 2018-04-22, the OpenDota API is limited to 50,000 free calls per month and 60 requests/minute** We offer a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more. 
 *
 * OpenAPI spec version: 17.6.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * InlineResponse2008
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-16T13:08:16.611+01:00")
public class InlineResponse2008 {
  @SerializedName("field")
  private String field = null;

  @SerializedName("n")
  private Integer n = null;

  @SerializedName("sum")
  private Integer sum = null;

  public InlineResponse2008 field(String field) {
    this.field = field;
    return this;
  }

   /**
   * field
   * @return field
  **/
  @ApiModelProperty(value = "field")
  public String getField() {
    return field;
  }

  public void setField(String field) {
    this.field = field;
  }

  public InlineResponse2008 n(Integer n) {
    this.n = n;
    return this;
  }

   /**
   * number
   * @return n
  **/
  @ApiModelProperty(value = "number")
  public Integer getN() {
    return n;
  }

  public void setN(Integer n) {
    this.n = n;
  }

  public InlineResponse2008 sum(Integer sum) {
    this.sum = sum;
    return this;
  }

   /**
   * sum
   * @return sum
  **/
  @ApiModelProperty(value = "sum")
  public Integer getSum() {
    return sum;
  }

  public void setSum(Integer sum) {
    this.sum = sum;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2008 inlineResponse2008 = (InlineResponse2008) o;
    return Objects.equals(this.field, inlineResponse2008.field) &&
        Objects.equals(this.n, inlineResponse2008.n) &&
        Objects.equals(this.sum, inlineResponse2008.sum);
  }

  @Override
  public int hashCode() {
    return Objects.hash(field, n, sum);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2008 {\n");
    
    sb.append("    field: ").append(toIndentedString(field)).append("\n");
    sb.append("    n: ").append(toIndentedString(n)).append("\n");
    sb.append("    sum: ").append(toIndentedString(sum)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

