/*
 * OpenDota API
 * # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  **Beginning 2018-04-22, the OpenDota API is limited to 50,000 free calls per month and 60 requests/minute** We offer a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more. 
 *
 * OpenAPI spec version: 17.6.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * InlineResponse20033
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-16T13:08:16.611+01:00")
public class InlineResponse20033 {
  @SerializedName("scenario")
  private String scenario = null;

  @SerializedName("is_radiant")
  private Boolean isRadiant = null;

  @SerializedName("region")
  private Integer region = null;

  @SerializedName("games")
  private String games = null;

  @SerializedName("wins")
  private String wins = null;

  public InlineResponse20033 scenario(String scenario) {
    this.scenario = scenario;
    return this;
  }

   /**
   * The scenario&#39;s name or description
   * @return scenario
  **/
  @ApiModelProperty(value = "The scenario's name or description")
  public String getScenario() {
    return scenario;
  }

  public void setScenario(String scenario) {
    this.scenario = scenario;
  }

  public InlineResponse20033 isRadiant(Boolean isRadiant) {
    this.isRadiant = isRadiant;
    return this;
  }

   /**
   * Boolean indicating whether Radiant executed this scenario
   * @return isRadiant
  **/
  @ApiModelProperty(value = "Boolean indicating whether Radiant executed this scenario")
  public Boolean isIsRadiant() {
    return isRadiant;
  }

  public void setIsRadiant(Boolean isRadiant) {
    this.isRadiant = isRadiant;
  }

  public InlineResponse20033 region(Integer region) {
    this.region = region;
    return this;
  }

   /**
   * Region the game was played in
   * @return region
  **/
  @ApiModelProperty(value = "Region the game was played in")
  public Integer getRegion() {
    return region;
  }

  public void setRegion(Integer region) {
    this.region = region;
  }

  public InlineResponse20033 games(String games) {
    this.games = games;
    return this;
  }

   /**
   * The number of games where this scenario occurred
   * @return games
  **/
  @ApiModelProperty(value = "The number of games where this scenario occurred")
  public String getGames() {
    return games;
  }

  public void setGames(String games) {
    this.games = games;
  }

  public InlineResponse20033 wins(String wins) {
    this.wins = wins;
    return this;
  }

   /**
   * The number of games won where this scenario occured
   * @return wins
  **/
  @ApiModelProperty(value = "The number of games won where this scenario occured")
  public String getWins() {
    return wins;
  }

  public void setWins(String wins) {
    this.wins = wins;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20033 inlineResponse20033 = (InlineResponse20033) o;
    return Objects.equals(this.scenario, inlineResponse20033.scenario) &&
        Objects.equals(this.isRadiant, inlineResponse20033.isRadiant) &&
        Objects.equals(this.region, inlineResponse20033.region) &&
        Objects.equals(this.games, inlineResponse20033.games) &&
        Objects.equals(this.wins, inlineResponse20033.wins);
  }

  @Override
  public int hashCode() {
    return Objects.hash(scenario, isRadiant, region, games, wins);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20033 {\n");
    
    sb.append("    scenario: ").append(toIndentedString(scenario)).append("\n");
    sb.append("    isRadiant: ").append(toIndentedString(isRadiant)).append("\n");
    sb.append("    region: ").append(toIndentedString(region)).append("\n");
    sb.append("    games: ").append(toIndentedString(games)).append("\n");
    sb.append("    wins: ").append(toIndentedString(wins)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

