/*
 * OpenDota API
 * # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  **Beginning 2018-04-22, the OpenDota API is limited to 50,000 free calls per month and 60 requests/minute** We offer a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more. 
 *
 * OpenAPI spec version: 17.6.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * InlineResponse20026
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-16T13:08:16.611+01:00")
public class InlineResponse20026 {
  @SerializedName("team_id")
  private Integer teamId = null;

  @SerializedName("rating")
  private BigDecimal rating = null;

  @SerializedName("wins")
  private Integer wins = null;

  @SerializedName("losses")
  private Integer losses = null;

  @SerializedName("last_match_time")
  private Integer lastMatchTime = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("tag")
  private String tag = null;

  public InlineResponse20026 teamId(Integer teamId) {
    this.teamId = teamId;
    return this;
  }

   /**
   * Team&#39;s identifier
   * @return teamId
  **/
  @ApiModelProperty(value = "Team's identifier")
  public Integer getTeamId() {
    return teamId;
  }

  public void setTeamId(Integer teamId) {
    this.teamId = teamId;
  }

  public InlineResponse20026 rating(BigDecimal rating) {
    this.rating = rating;
    return this;
  }

   /**
   * The Elo rating of the team
   * @return rating
  **/
  @ApiModelProperty(value = "The Elo rating of the team")
  public BigDecimal getRating() {
    return rating;
  }

  public void setRating(BigDecimal rating) {
    this.rating = rating;
  }

  public InlineResponse20026 wins(Integer wins) {
    this.wins = wins;
    return this;
  }

   /**
   * The number of games won by this team
   * @return wins
  **/
  @ApiModelProperty(value = "The number of games won by this team")
  public Integer getWins() {
    return wins;
  }

  public void setWins(Integer wins) {
    this.wins = wins;
  }

  public InlineResponse20026 losses(Integer losses) {
    this.losses = losses;
    return this;
  }

   /**
   * The number of losses by this team
   * @return losses
  **/
  @ApiModelProperty(value = "The number of losses by this team")
  public Integer getLosses() {
    return losses;
  }

  public void setLosses(Integer losses) {
    this.losses = losses;
  }

  public InlineResponse20026 lastMatchTime(Integer lastMatchTime) {
    this.lastMatchTime = lastMatchTime;
    return this;
  }

   /**
   * The Unix timestamp of the last match played by this team
   * @return lastMatchTime
  **/
  @ApiModelProperty(value = "The Unix timestamp of the last match played by this team")
  public Integer getLastMatchTime() {
    return lastMatchTime;
  }

  public void setLastMatchTime(Integer lastMatchTime) {
    this.lastMatchTime = lastMatchTime;
  }

  public InlineResponse20026 name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Team name, eg. &#39;Newbee&#39;
   * @return name
  **/
  @ApiModelProperty(value = "Team name, eg. 'Newbee'")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public InlineResponse20026 tag(String tag) {
    this.tag = tag;
    return this;
  }

   /**
   * The team tag/abbreviation
   * @return tag
  **/
  @ApiModelProperty(value = "The team tag/abbreviation")
  public String getTag() {
    return tag;
  }

  public void setTag(String tag) {
    this.tag = tag;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20026 inlineResponse20026 = (InlineResponse20026) o;
    return Objects.equals(this.teamId, inlineResponse20026.teamId) &&
        Objects.equals(this.rating, inlineResponse20026.rating) &&
        Objects.equals(this.wins, inlineResponse20026.wins) &&
        Objects.equals(this.losses, inlineResponse20026.losses) &&
        Objects.equals(this.lastMatchTime, inlineResponse20026.lastMatchTime) &&
        Objects.equals(this.name, inlineResponse20026.name) &&
        Objects.equals(this.tag, inlineResponse20026.tag);
  }

  @Override
  public int hashCode() {
    return Objects.hash(teamId, rating, wins, losses, lastMatchTime, name, tag);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20026 {\n");
    
    sb.append("    teamId: ").append(toIndentedString(teamId)).append("\n");
    sb.append("    rating: ").append(toIndentedString(rating)).append("\n");
    sb.append("    wins: ").append(toIndentedString(wins)).append("\n");
    sb.append("    losses: ").append(toIndentedString(losses)).append("\n");
    sb.append("    lastMatchTime: ").append(toIndentedString(lastMatchTime)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    tag: ").append(toIndentedString(tag)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

