/*
 * OpenDota API
 * # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  **Beginning 2018-04-22, the OpenDota API is limited to 50,000 free calls per month and 60 requests/minute** We offer a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more. 
 *
 * OpenAPI spec version: 17.6.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.PlayersaccountIdmatchesHeroes;
import java.io.IOException;

/**
 * Object containing information on the match
 */
@ApiModel(description = "Object containing information on the match")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-16T13:08:16.611+01:00")
public class InlineResponse2004 {
  @SerializedName("match_id")
  private Integer matchId = null;

  @SerializedName("player_slot")
  private Integer playerSlot = null;

  @SerializedName("radiant_win")
  private Boolean radiantWin = null;

  @SerializedName("duration")
  private Integer duration = null;

  @SerializedName("game_mode")
  private Integer gameMode = null;

  @SerializedName("lobby_type")
  private Integer lobbyType = null;

  @SerializedName("hero_id")
  private Integer heroId = null;

  @SerializedName("start_time")
  private Integer startTime = null;

  @SerializedName("version")
  private Integer version = null;

  @SerializedName("kills")
  private Integer kills = null;

  @SerializedName("deaths")
  private Integer deaths = null;

  @SerializedName("assists")
  private Integer assists = null;

  @SerializedName("skill")
  private Integer skill = null;

  @SerializedName("party_size")
  private Integer partySize = null;

  @SerializedName("heroes")
  private PlayersaccountIdmatchesHeroes heroes = null;

  public InlineResponse2004 matchId(Integer matchId) {
    this.matchId = matchId;
    return this;
  }

   /**
   * Match ID
   * @return matchId
  **/
  @ApiModelProperty(value = "Match ID")
  public Integer getMatchId() {
    return matchId;
  }

  public void setMatchId(Integer matchId) {
    this.matchId = matchId;
  }

  public InlineResponse2004 playerSlot(Integer playerSlot) {
    this.playerSlot = playerSlot;
    return this;
  }

   /**
   * Which slot the player is in. 0-127 are Radiant, 128-255 are Dire
   * @return playerSlot
  **/
  @ApiModelProperty(value = "Which slot the player is in. 0-127 are Radiant, 128-255 are Dire")
  public Integer getPlayerSlot() {
    return playerSlot;
  }

  public void setPlayerSlot(Integer playerSlot) {
    this.playerSlot = playerSlot;
  }

  public InlineResponse2004 radiantWin(Boolean radiantWin) {
    this.radiantWin = radiantWin;
    return this;
  }

   /**
   * Boolean indicating whether Radiant won the match
   * @return radiantWin
  **/
  @ApiModelProperty(value = "Boolean indicating whether Radiant won the match")
  public Boolean isRadiantWin() {
    return radiantWin;
  }

  public void setRadiantWin(Boolean radiantWin) {
    this.radiantWin = radiantWin;
  }

  public InlineResponse2004 duration(Integer duration) {
    this.duration = duration;
    return this;
  }

   /**
   * Duration of the game in seconds
   * @return duration
  **/
  @ApiModelProperty(value = "Duration of the game in seconds")
  public Integer getDuration() {
    return duration;
  }

  public void setDuration(Integer duration) {
    this.duration = duration;
  }

  public InlineResponse2004 gameMode(Integer gameMode) {
    this.gameMode = gameMode;
    return this;
  }

   /**
   * Integer corresponding to game mode played. List of constants can be found here: https://github.com/odota/dotaconstants/blob/master/json/game_mode.json
   * @return gameMode
  **/
  @ApiModelProperty(value = "Integer corresponding to game mode played. List of constants can be found here: https://github.com/odota/dotaconstants/blob/master/json/game_mode.json")
  public Integer getGameMode() {
    return gameMode;
  }

  public void setGameMode(Integer gameMode) {
    this.gameMode = gameMode;
  }

  public InlineResponse2004 lobbyType(Integer lobbyType) {
    this.lobbyType = lobbyType;
    return this;
  }

   /**
   * Integer corresponding to lobby type of match. List of constants can be found here: https://github.com/odota/dotaconstants/blob/master/json/lobby_type.json
   * @return lobbyType
  **/
  @ApiModelProperty(value = "Integer corresponding to lobby type of match. List of constants can be found here: https://github.com/odota/dotaconstants/blob/master/json/lobby_type.json")
  public Integer getLobbyType() {
    return lobbyType;
  }

  public void setLobbyType(Integer lobbyType) {
    this.lobbyType = lobbyType;
  }

  public InlineResponse2004 heroId(Integer heroId) {
    this.heroId = heroId;
    return this;
  }

   /**
   * The ID value of the hero played
   * @return heroId
  **/
  @ApiModelProperty(value = "The ID value of the hero played")
  public Integer getHeroId() {
    return heroId;
  }

  public void setHeroId(Integer heroId) {
    this.heroId = heroId;
  }

  public InlineResponse2004 startTime(Integer startTime) {
    this.startTime = startTime;
    return this;
  }

   /**
   * Time the game started in seconds since 1970
   * @return startTime
  **/
  @ApiModelProperty(value = "Time the game started in seconds since 1970")
  public Integer getStartTime() {
    return startTime;
  }

  public void setStartTime(Integer startTime) {
    this.startTime = startTime;
  }

  public InlineResponse2004 version(Integer version) {
    this.version = version;
    return this;
  }

   /**
   * version
   * @return version
  **/
  @ApiModelProperty(value = "version")
  public Integer getVersion() {
    return version;
  }

  public void setVersion(Integer version) {
    this.version = version;
  }

  public InlineResponse2004 kills(Integer kills) {
    this.kills = kills;
    return this;
  }

   /**
   * Total kills the player had at the end of the game
   * @return kills
  **/
  @ApiModelProperty(value = "Total kills the player had at the end of the game")
  public Integer getKills() {
    return kills;
  }

  public void setKills(Integer kills) {
    this.kills = kills;
  }

  public InlineResponse2004 deaths(Integer deaths) {
    this.deaths = deaths;
    return this;
  }

   /**
   * Total deaths the player had at the end of the game
   * @return deaths
  **/
  @ApiModelProperty(value = "Total deaths the player had at the end of the game")
  public Integer getDeaths() {
    return deaths;
  }

  public void setDeaths(Integer deaths) {
    this.deaths = deaths;
  }

  public InlineResponse2004 assists(Integer assists) {
    this.assists = assists;
    return this;
  }

   /**
   * Total assists the player had at the end of the game
   * @return assists
  **/
  @ApiModelProperty(value = "Total assists the player had at the end of the game")
  public Integer getAssists() {
    return assists;
  }

  public void setAssists(Integer assists) {
    this.assists = assists;
  }

  public InlineResponse2004 skill(Integer skill) {
    this.skill = skill;
    return this;
  }

   /**
   * Skill bracket assigned by Valve (Normal, High, Very High)
   * @return skill
  **/
  @ApiModelProperty(value = "Skill bracket assigned by Valve (Normal, High, Very High)")
  public Integer getSkill() {
    return skill;
  }

  public void setSkill(Integer skill) {
    this.skill = skill;
  }

  public InlineResponse2004 partySize(Integer partySize) {
    this.partySize = partySize;
    return this;
  }

   /**
   * Size of the player&#39;s party
   * @return partySize
  **/
  @ApiModelProperty(value = "Size of the player's party")
  public Integer getPartySize() {
    return partySize;
  }

  public void setPartySize(Integer partySize) {
    this.partySize = partySize;
  }

  public InlineResponse2004 heroes(PlayersaccountIdmatchesHeroes heroes) {
    this.heroes = heroes;
    return this;
  }

   /**
   * Get heroes
   * @return heroes
  **/
  @ApiModelProperty(value = "")
  public PlayersaccountIdmatchesHeroes getHeroes() {
    return heroes;
  }

  public void setHeroes(PlayersaccountIdmatchesHeroes heroes) {
    this.heroes = heroes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2004 inlineResponse2004 = (InlineResponse2004) o;
    return Objects.equals(this.matchId, inlineResponse2004.matchId) &&
        Objects.equals(this.playerSlot, inlineResponse2004.playerSlot) &&
        Objects.equals(this.radiantWin, inlineResponse2004.radiantWin) &&
        Objects.equals(this.duration, inlineResponse2004.duration) &&
        Objects.equals(this.gameMode, inlineResponse2004.gameMode) &&
        Objects.equals(this.lobbyType, inlineResponse2004.lobbyType) &&
        Objects.equals(this.heroId, inlineResponse2004.heroId) &&
        Objects.equals(this.startTime, inlineResponse2004.startTime) &&
        Objects.equals(this.version, inlineResponse2004.version) &&
        Objects.equals(this.kills, inlineResponse2004.kills) &&
        Objects.equals(this.deaths, inlineResponse2004.deaths) &&
        Objects.equals(this.assists, inlineResponse2004.assists) &&
        Objects.equals(this.skill, inlineResponse2004.skill) &&
        Objects.equals(this.partySize, inlineResponse2004.partySize) &&
        Objects.equals(this.heroes, inlineResponse2004.heroes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(matchId, playerSlot, radiantWin, duration, gameMode, lobbyType, heroId, startTime, version, kills, deaths, assists, skill, partySize, heroes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2004 {\n");
    
    sb.append("    matchId: ").append(toIndentedString(matchId)).append("\n");
    sb.append("    playerSlot: ").append(toIndentedString(playerSlot)).append("\n");
    sb.append("    radiantWin: ").append(toIndentedString(radiantWin)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    gameMode: ").append(toIndentedString(gameMode)).append("\n");
    sb.append("    lobbyType: ").append(toIndentedString(lobbyType)).append("\n");
    sb.append("    heroId: ").append(toIndentedString(heroId)).append("\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    kills: ").append(toIndentedString(kills)).append("\n");
    sb.append("    deaths: ").append(toIndentedString(deaths)).append("\n");
    sb.append("    assists: ").append(toIndentedString(assists)).append("\n");
    sb.append("    skill: ").append(toIndentedString(skill)).append("\n");
    sb.append("    partySize: ").append(toIndentedString(partySize)).append("\n");
    sb.append("    heroes: ").append(toIndentedString(heroes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

