/*
 * OpenDota API
 * # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  **Beginning 2018-04-22, the OpenDota API is limited to 50,000 free calls per month and 60 requests/minute** We offer a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more. 
 *
 * OpenAPI spec version: 17.6.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * InlineResponse20029
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-16T13:08:16.611+01:00")
public class InlineResponse20029 {
  @SerializedName("match_id")
  private Integer matchId = null;

  @SerializedName("cluster")
  private Integer cluster = null;

  @SerializedName("replay_salt")
  private Integer replaySalt = null;

  public InlineResponse20029 matchId(Integer matchId) {
    this.matchId = matchId;
    return this;
  }

   /**
   * match_id
   * @return matchId
  **/
  @ApiModelProperty(value = "match_id")
  public Integer getMatchId() {
    return matchId;
  }

  public void setMatchId(Integer matchId) {
    this.matchId = matchId;
  }

  public InlineResponse20029 cluster(Integer cluster) {
    this.cluster = cluster;
    return this;
  }

   /**
   * cluster
   * @return cluster
  **/
  @ApiModelProperty(value = "cluster")
  public Integer getCluster() {
    return cluster;
  }

  public void setCluster(Integer cluster) {
    this.cluster = cluster;
  }

  public InlineResponse20029 replaySalt(Integer replaySalt) {
    this.replaySalt = replaySalt;
    return this;
  }

   /**
   * replay_salt
   * @return replaySalt
  **/
  @ApiModelProperty(value = "replay_salt")
  public Integer getReplaySalt() {
    return replaySalt;
  }

  public void setReplaySalt(Integer replaySalt) {
    this.replaySalt = replaySalt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20029 inlineResponse20029 = (InlineResponse20029) o;
    return Objects.equals(this.matchId, inlineResponse20029.matchId) &&
        Objects.equals(this.cluster, inlineResponse20029.cluster) &&
        Objects.equals(this.replaySalt, inlineResponse20029.replaySalt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(matchId, cluster, replaySalt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20029 {\n");
    
    sb.append("    matchId: ").append(toIndentedString(matchId)).append("\n");
    sb.append("    cluster: ").append(toIndentedString(cluster)).append("\n");
    sb.append("    replaySalt: ").append(toIndentedString(replaySalt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

