/*
 * OpenDota API
 * # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  **Beginning 2018-04-22, the OpenDota API is limited to 50,000 free calls per month and 60 requests/minute** We offer a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more. 
 *
 * OpenAPI spec version: 17.6.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * cheese
 */
@ApiModel(description = "cheese")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-16T13:08:16.611+01:00")
public class InlineResponse20016Cheese {
  @SerializedName("cheese")
  private String cheese = null;

  @SerializedName("goal")
  private String goal = null;

  public InlineResponse20016Cheese cheese(String cheese) {
    this.cheese = cheese;
    return this;
  }

   /**
   * cheese
   * @return cheese
  **/
  @ApiModelProperty(value = "cheese")
  public String getCheese() {
    return cheese;
  }

  public void setCheese(String cheese) {
    this.cheese = cheese;
  }

  public InlineResponse20016Cheese goal(String goal) {
    this.goal = goal;
    return this;
  }

   /**
   * goal
   * @return goal
  **/
  @ApiModelProperty(value = "goal")
  public String getGoal() {
    return goal;
  }

  public void setGoal(String goal) {
    this.goal = goal;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20016Cheese inlineResponse20016Cheese = (InlineResponse20016Cheese) o;
    return Objects.equals(this.cheese, inlineResponse20016Cheese.cheese) &&
        Objects.equals(this.goal, inlineResponse20016Cheese.goal);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cheese, goal);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20016Cheese {\n");
    
    sb.append("    cheese: ").append(toIndentedString(cheese)).append("\n");
    sb.append("    goal: ").append(toIndentedString(goal)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

