/*
 * OpenDota API
 * # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  **Beginning 2018-04-22, the OpenDota API is limited to 50,000 free calls per month and 60 requests/minute** We offer a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more. 
 *
 * OpenAPI spec version: 17.6.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.InlineResponse20017CountryMmr;
import io.swagger.client.model.InlineResponse20017Mmr;
import io.swagger.client.model.InlineResponse20017Ranks;
import java.io.IOException;

/**
 * InlineResponse20017
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-16T13:08:16.611+01:00")
public class InlineResponse20017 {
  @SerializedName("ranks")
  private InlineResponse20017Ranks ranks = null;

  @SerializedName("mmr")
  private InlineResponse20017Mmr mmr = null;

  @SerializedName("country_mmr")
  private InlineResponse20017CountryMmr countryMmr = null;

  public InlineResponse20017 ranks(InlineResponse20017Ranks ranks) {
    this.ranks = ranks;
    return this;
  }

   /**
   * Get ranks
   * @return ranks
  **/
  @ApiModelProperty(value = "")
  public InlineResponse20017Ranks getRanks() {
    return ranks;
  }

  public void setRanks(InlineResponse20017Ranks ranks) {
    this.ranks = ranks;
  }

  public InlineResponse20017 mmr(InlineResponse20017Mmr mmr) {
    this.mmr = mmr;
    return this;
  }

   /**
   * Get mmr
   * @return mmr
  **/
  @ApiModelProperty(value = "")
  public InlineResponse20017Mmr getMmr() {
    return mmr;
  }

  public void setMmr(InlineResponse20017Mmr mmr) {
    this.mmr = mmr;
  }

  public InlineResponse20017 countryMmr(InlineResponse20017CountryMmr countryMmr) {
    this.countryMmr = countryMmr;
    return this;
  }

   /**
   * Get countryMmr
   * @return countryMmr
  **/
  @ApiModelProperty(value = "")
  public InlineResponse20017CountryMmr getCountryMmr() {
    return countryMmr;
  }

  public void setCountryMmr(InlineResponse20017CountryMmr countryMmr) {
    this.countryMmr = countryMmr;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20017 inlineResponse20017 = (InlineResponse20017) o;
    return Objects.equals(this.ranks, inlineResponse20017.ranks) &&
        Objects.equals(this.mmr, inlineResponse20017.mmr) &&
        Objects.equals(this.countryMmr, inlineResponse20017.countryMmr);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ranks, mmr, countryMmr);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20017 {\n");
    
    sb.append("    ranks: ").append(toIndentedString(ranks)).append("\n");
    sb.append("    mmr: ").append(toIndentedString(mmr)).append("\n");
    sb.append("    countryMmr: ").append(toIndentedString(countryMmr)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

