/*
 * OpenDota API
 * # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  **Beginning 2018-04-22, the OpenDota API is limited to 50,000 free calls per month and 60 requests/minute** We offer a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more. 
 *
 * OpenAPI spec version: 17.6.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.InlineResponse20016Cheese;
import java.io.IOException;

/**
 * InlineResponse20016
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-16T13:08:16.611+01:00")
public class InlineResponse20016 {
  @SerializedName("banner")
  private Object banner = null;

  @SerializedName("cheese")
  private InlineResponse20016Cheese cheese = null;

  public InlineResponse20016 banner(Object banner) {
    this.banner = banner;
    return this;
  }

   /**
   * banner
   * @return banner
  **/
  @ApiModelProperty(value = "banner")
  public Object getBanner() {
    return banner;
  }

  public void setBanner(Object banner) {
    this.banner = banner;
  }

  public InlineResponse20016 cheese(InlineResponse20016Cheese cheese) {
    this.cheese = cheese;
    return this;
  }

   /**
   * Get cheese
   * @return cheese
  **/
  @ApiModelProperty(value = "")
  public InlineResponse20016Cheese getCheese() {
    return cheese;
  }

  public void setCheese(InlineResponse20016Cheese cheese) {
    this.cheese = cheese;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20016 inlineResponse20016 = (InlineResponse20016) o;
    return Objects.equals(this.banner, inlineResponse20016.banner) &&
        Objects.equals(this.cheese, inlineResponse20016.cheese);
  }

  @Override
  public int hashCode() {
    return Objects.hash(banner, cheese);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20016 {\n");
    
    sb.append("    banner: ").append(toIndentedString(banner)).append("\n");
    sb.append("    cheese: ").append(toIndentedString(cheese)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

