/*
 * OpenDota API
 * # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  **Beginning 2018-04-22, the OpenDota API is limited to 50,000 free calls per month and 60 requests/minute** We offer a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more. 
 *
 * OpenAPI spec version: 17.6.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * profile
 */
@ApiModel(description = "profile")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-16T13:08:16.611+01:00")
public class InlineResponse2001Profile {
  @SerializedName("account_id")
  private Integer accountId = null;

  @SerializedName("personaname")
  private String personaname = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("cheese")
  private Integer cheese = null;

  @SerializedName("steamid")
  private String steamid = null;

  @SerializedName("avatar")
  private String avatar = null;

  @SerializedName("avatarmedium")
  private String avatarmedium = null;

  @SerializedName("avatarfull")
  private String avatarfull = null;

  @SerializedName("profileurl")
  private String profileurl = null;

  @SerializedName("last_login")
  private String lastLogin = null;

  @SerializedName("loccountrycode")
  private String loccountrycode = null;

  @SerializedName("is_contributor")
  private Boolean isContributor = false;

  public InlineResponse2001Profile accountId(Integer accountId) {
    this.accountId = accountId;
    return this;
  }

   /**
   * account_id
   * @return accountId
  **/
  @ApiModelProperty(value = "account_id")
  public Integer getAccountId() {
    return accountId;
  }

  public void setAccountId(Integer accountId) {
    this.accountId = accountId;
  }

  public InlineResponse2001Profile personaname(String personaname) {
    this.personaname = personaname;
    return this;
  }

   /**
   * personaname
   * @return personaname
  **/
  @ApiModelProperty(value = "personaname")
  public String getPersonaname() {
    return personaname;
  }

  public void setPersonaname(String personaname) {
    this.personaname = personaname;
  }

  public InlineResponse2001Profile name(String name) {
    this.name = name;
    return this;
  }

   /**
   * name
   * @return name
  **/
  @ApiModelProperty(value = "name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public InlineResponse2001Profile cheese(Integer cheese) {
    this.cheese = cheese;
    return this;
  }

   /**
   * cheese
   * @return cheese
  **/
  @ApiModelProperty(value = "cheese")
  public Integer getCheese() {
    return cheese;
  }

  public void setCheese(Integer cheese) {
    this.cheese = cheese;
  }

  public InlineResponse2001Profile steamid(String steamid) {
    this.steamid = steamid;
    return this;
  }

   /**
   * steamid
   * @return steamid
  **/
  @ApiModelProperty(value = "steamid")
  public String getSteamid() {
    return steamid;
  }

  public void setSteamid(String steamid) {
    this.steamid = steamid;
  }

  public InlineResponse2001Profile avatar(String avatar) {
    this.avatar = avatar;
    return this;
  }

   /**
   * avatar
   * @return avatar
  **/
  @ApiModelProperty(value = "avatar")
  public String getAvatar() {
    return avatar;
  }

  public void setAvatar(String avatar) {
    this.avatar = avatar;
  }

  public InlineResponse2001Profile avatarmedium(String avatarmedium) {
    this.avatarmedium = avatarmedium;
    return this;
  }

   /**
   * avatarmedium
   * @return avatarmedium
  **/
  @ApiModelProperty(value = "avatarmedium")
  public String getAvatarmedium() {
    return avatarmedium;
  }

  public void setAvatarmedium(String avatarmedium) {
    this.avatarmedium = avatarmedium;
  }

  public InlineResponse2001Profile avatarfull(String avatarfull) {
    this.avatarfull = avatarfull;
    return this;
  }

   /**
   * avatarfull
   * @return avatarfull
  **/
  @ApiModelProperty(value = "avatarfull")
  public String getAvatarfull() {
    return avatarfull;
  }

  public void setAvatarfull(String avatarfull) {
    this.avatarfull = avatarfull;
  }

  public InlineResponse2001Profile profileurl(String profileurl) {
    this.profileurl = profileurl;
    return this;
  }

   /**
   * profileurl
   * @return profileurl
  **/
  @ApiModelProperty(value = "profileurl")
  public String getProfileurl() {
    return profileurl;
  }

  public void setProfileurl(String profileurl) {
    this.profileurl = profileurl;
  }

  public InlineResponse2001Profile lastLogin(String lastLogin) {
    this.lastLogin = lastLogin;
    return this;
  }

   /**
   * last_login
   * @return lastLogin
  **/
  @ApiModelProperty(value = "last_login")
  public String getLastLogin() {
    return lastLogin;
  }

  public void setLastLogin(String lastLogin) {
    this.lastLogin = lastLogin;
  }

  public InlineResponse2001Profile loccountrycode(String loccountrycode) {
    this.loccountrycode = loccountrycode;
    return this;
  }

   /**
   * loccountrycode
   * @return loccountrycode
  **/
  @ApiModelProperty(value = "loccountrycode")
  public String getLoccountrycode() {
    return loccountrycode;
  }

  public void setLoccountrycode(String loccountrycode) {
    this.loccountrycode = loccountrycode;
  }

  public InlineResponse2001Profile isContributor(Boolean isContributor) {
    this.isContributor = isContributor;
    return this;
  }

   /**
   * Boolean indicating if the user contributed to the development of OpenDota
   * @return isContributor
  **/
  @ApiModelProperty(value = "Boolean indicating if the user contributed to the development of OpenDota")
  public Boolean isIsContributor() {
    return isContributor;
  }

  public void setIsContributor(Boolean isContributor) {
    this.isContributor = isContributor;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2001Profile inlineResponse2001Profile = (InlineResponse2001Profile) o;
    return Objects.equals(this.accountId, inlineResponse2001Profile.accountId) &&
        Objects.equals(this.personaname, inlineResponse2001Profile.personaname) &&
        Objects.equals(this.name, inlineResponse2001Profile.name) &&
        Objects.equals(this.cheese, inlineResponse2001Profile.cheese) &&
        Objects.equals(this.steamid, inlineResponse2001Profile.steamid) &&
        Objects.equals(this.avatar, inlineResponse2001Profile.avatar) &&
        Objects.equals(this.avatarmedium, inlineResponse2001Profile.avatarmedium) &&
        Objects.equals(this.avatarfull, inlineResponse2001Profile.avatarfull) &&
        Objects.equals(this.profileurl, inlineResponse2001Profile.profileurl) &&
        Objects.equals(this.lastLogin, inlineResponse2001Profile.lastLogin) &&
        Objects.equals(this.loccountrycode, inlineResponse2001Profile.loccountrycode) &&
        Objects.equals(this.isContributor, inlineResponse2001Profile.isContributor);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountId, personaname, name, cheese, steamid, avatar, avatarmedium, avatarfull, profileurl, lastLogin, loccountrycode, isContributor);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2001Profile {\n");
    
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    personaname: ").append(toIndentedString(personaname)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    cheese: ").append(toIndentedString(cheese)).append("\n");
    sb.append("    steamid: ").append(toIndentedString(steamid)).append("\n");
    sb.append("    avatar: ").append(toIndentedString(avatar)).append("\n");
    sb.append("    avatarmedium: ").append(toIndentedString(avatarmedium)).append("\n");
    sb.append("    avatarfull: ").append(toIndentedString(avatarfull)).append("\n");
    sb.append("    profileurl: ").append(toIndentedString(profileurl)).append("\n");
    sb.append("    lastLogin: ").append(toIndentedString(lastLogin)).append("\n");
    sb.append("    loccountrycode: ").append(toIndentedString(loccountrycode)).append("\n");
    sb.append("    isContributor: ").append(toIndentedString(isContributor)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

