/*
 * OpenDota API
 * # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  **Beginning 2018-04-22, the OpenDota API is limited to 50,000 free calls per month and 60 requests/minute** We offer a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more. 
 *
 * OpenAPI spec version: 17.6.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * InlineResponse20021
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-16T13:08:16.611+01:00")
public class InlineResponse20021 {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("localized_name")
  private String localizedName = null;

  @SerializedName("primary_attr")
  private String primaryAttr = null;

  @SerializedName("attack_type")
  private String attackType = null;

  @SerializedName("roles")
  private List<String> roles = null;

  public InlineResponse20021 id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Numeric identifier for the hero object
   * @return id
  **/
  @ApiModelProperty(value = "Numeric identifier for the hero object")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public InlineResponse20021 name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Dota hero command name, e.g. &#39;npc_dota_hero_antimage&#39;
   * @return name
  **/
  @ApiModelProperty(value = "Dota hero command name, e.g. 'npc_dota_hero_antimage'")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public InlineResponse20021 localizedName(String localizedName) {
    this.localizedName = localizedName;
    return this;
  }

   /**
   * Hero name, e.g. &#39;Anti-Mage&#39;
   * @return localizedName
  **/
  @ApiModelProperty(value = "Hero name, e.g. 'Anti-Mage'")
  public String getLocalizedName() {
    return localizedName;
  }

  public void setLocalizedName(String localizedName) {
    this.localizedName = localizedName;
  }

  public InlineResponse20021 primaryAttr(String primaryAttr) {
    this.primaryAttr = primaryAttr;
    return this;
  }

   /**
   * Hero primary shorthand attribute name, e.g. &#39;agi&#39;
   * @return primaryAttr
  **/
  @ApiModelProperty(value = "Hero primary shorthand attribute name, e.g. 'agi'")
  public String getPrimaryAttr() {
    return primaryAttr;
  }

  public void setPrimaryAttr(String primaryAttr) {
    this.primaryAttr = primaryAttr;
  }

  public InlineResponse20021 attackType(String attackType) {
    this.attackType = attackType;
    return this;
  }

   /**
   * Hero attack type, either &#39;Melee&#39; or &#39;Ranged&#39;
   * @return attackType
  **/
  @ApiModelProperty(value = "Hero attack type, either 'Melee' or 'Ranged'")
  public String getAttackType() {
    return attackType;
  }

  public void setAttackType(String attackType) {
    this.attackType = attackType;
  }

  public InlineResponse20021 roles(List<String> roles) {
    this.roles = roles;
    return this;
  }

  public InlineResponse20021 addRolesItem(String rolesItem) {
    if (this.roles == null) {
      this.roles = new ArrayList<String>();
    }
    this.roles.add(rolesItem);
    return this;
  }

   /**
   * Get roles
   * @return roles
  **/
  @ApiModelProperty(value = "")
  public List<String> getRoles() {
    return roles;
  }

  public void setRoles(List<String> roles) {
    this.roles = roles;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20021 inlineResponse20021 = (InlineResponse20021) o;
    return Objects.equals(this.id, inlineResponse20021.id) &&
        Objects.equals(this.name, inlineResponse20021.name) &&
        Objects.equals(this.localizedName, inlineResponse20021.localizedName) &&
        Objects.equals(this.primaryAttr, inlineResponse20021.primaryAttr) &&
        Objects.equals(this.attackType, inlineResponse20021.attackType) &&
        Objects.equals(this.roles, inlineResponse20021.roles);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, localizedName, primaryAttr, attackType, roles);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20021 {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    localizedName: ").append(toIndentedString(localizedName)).append("\n");
    sb.append("    primaryAttr: ").append(toIndentedString(primaryAttr)).append("\n");
    sb.append("    attackType: ").append(toIndentedString(attackType)).append("\n");
    sb.append("    roles: ").append(toIndentedString(roles)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

