/*
 * OpenDota API
 * # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  **Beginning 2018-04-22, the OpenDota API is limited to 50,000 free calls per month and 60 requests/minute** We offer a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more. 
 *
 * OpenAPI spec version: 17.6.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.InlineResponse20031;
import io.swagger.client.model.InlineResponse20032;
import io.swagger.client.model.InlineResponse20033;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ScenariosApi
 */
@Ignore
public class ScenariosApiTest {

    private final ScenariosApi api = new ScenariosApi();

    
    /**
     * GET /scenarios/itemTimings
     *
     * Win rates for certain item timings on a hero for items that cost at least 1400 gold
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void scenariosItemTimingsGetTest() throws ApiException {
        String item = null;
        Integer heroId = null;
        List<InlineResponse20031> response = api.scenariosItemTimingsGet(item, heroId);

        // TODO: test validations
    }
    
    /**
     * GET /scenarios/laneRoles
     *
     * Win rates for heroes in certain lane roles
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void scenariosLaneRolesGetTest() throws ApiException {
        String laneRole = null;
        Integer heroId = null;
        List<InlineResponse20032> response = api.scenariosLaneRolesGet(laneRole, heroId);

        // TODO: test validations
    }
    
    /**
     * GET /scenarios/misc
     *
     * Miscellaneous team scenarios
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void scenariosMiscGetTest() throws ApiException {
        String scenario = null;
        List<InlineResponse20033> response = api.scenariosMiscGet(scenario);

        // TODO: test validations
    }
    
}
