/*
 * OpenDota API
 * # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  **Beginning 2018-04-22, the OpenDota API is limited to 50,000 free calls per month and 60 requests/minute** We offer a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more. 
 *
 * OpenAPI spec version: 17.6.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.InlineResponse20014;
import io.swagger.client.model.InlineResponse20026;
import io.swagger.client.model.InlineResponse20027;
import io.swagger.client.model.InlineResponse20028;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TeamsApi
 */
@Ignore
public class TeamsApiTest {

    private final TeamsApi api = new TeamsApi();

    
    /**
     * GET /teams
     *
     * Get team data
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void teamsGetTest() throws ApiException {
        List<InlineResponse20026> response = api.teamsGet();

        // TODO: test validations
    }
    
    /**
     * GET /teams/{team_id}
     *
     * Get data for a team
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void teamsTeamIdGetTest() throws ApiException {
        Integer teamId = null;
        InlineResponse20026 response = api.teamsTeamIdGet(teamId);

        // TODO: test validations
    }
    
    /**
     * GET /teams/{team_id}/heroes
     *
     * Get heroes for a team
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void teamsTeamIdHeroesGetTest() throws ApiException {
        Integer teamId = null;
        InlineResponse20028 response = api.teamsTeamIdHeroesGet(teamId);

        // TODO: test validations
    }
    
    /**
     * GET /teams/{team_id}/matches
     *
     * Get matches for a team
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void teamsTeamIdMatchesGetTest() throws ApiException {
        Integer teamId = null;
        InlineResponse20014 response = api.teamsTeamIdMatchesGet(teamId);

        // TODO: test validations
    }
    
    /**
     * GET /teams/{team_id}/players
     *
     * Get players who have played for a team
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void teamsTeamIdPlayersGetTest() throws ApiException {
        Integer teamId = null;
        InlineResponse20027 response = api.teamsTeamIdPlayersGet(teamId);

        // TODO: test validations
    }
    
}
